name: Run Promo Code Script 3

on:
  workflow_run:
    workflows: ["Trigger All Promo Code Scripts"]
    types:
      - requested

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run the script
        run: |
          python test.py
        continue-on-error: true

      - name: Upload promo codes as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: promo-codes
          path: ./promo_codes.txt
